### ISSUE TITLE
Pnpm Install: Spawn Error

### ISSUE THREAD

**Issue by milimyname** [indaco/svelte-iconoir#6]
Hi Mr. Indaco.

I was really looking forward to using it in my new project but couldn't install it. 

internal/child_process.js:408
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal (child_process.js:911:17)
    at spawn (pkg/prelude/bootstrap.js:2014:27)
    at spawn (/snapshot/dist/pnpm.cjs)
    at runCmd_ (/snapshot/dist/pnpm.cjs)
    at runCmd (/snapshot/dist/pnpm.cjs)
    at runPackageLifecycle (/snapshot/dist/pnpm.cjs)
    at Array.<anonymous> (/snapshot/dist/pnpm.cjs)
    at LOOP (/snapshot/dist/pnpm.cjs) {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}

**Comment by indaco** [comment]
Hi @milimyname,
please, provide your system info by running 

`npx envinfo --system --binaries`

Thanks

**Comment by milimyname** [comment]
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 1.86 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm

**Comment by indaco** [comment]
`pnpm --version` ?

**Comment by milimyname** [comment]
7.27.1

**Comment by indaco** [comment]
Did you try  with newer pnpm versions like v7.30.3 or the latest v8.1.0?

**Comment by milimyname** [comment]
I did. The same error. I wonder if u can install it to ur project. 

Packages: +54 -36
++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------
Progress: resolved 417, reused 373, downloaded 2, added 33, done
node_modules/.pnpm/@indaco+svelte-iconoir@4.1.0/node_modules/@indaco/svelte-iconoir: Running postinstall script...
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at spawn (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:83493:19)
    at runCmd_ (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99641:20)
    at runCmd (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99582:9)
    at runPackageLifecycle (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99549:7)
    at Array.<anonymous> (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99022:13)
    at LOOP (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99049:18)
    at chain (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99056:9)
    at lifecycle_ (/Users/mili.myname/Library/pnpm/global/5/.pnpm/pnpm@8.1.0/node_modules/pnpm/dist/pnpm.cjs:99523:7) {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}

**Comment by indaco** [comment]
ok, got it. it seems the problem is with the postinstall script where the package seems to do something wrong. I guess is something related to git...

will try to fix it now. Keep you posted

**Comment by indaco** [comment]
I'm going to release a fixed version
